name: Build
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: 'Build!'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 3
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        id: build
        uses: docker/build-push-action@v3
        with:
          push: false
          outputs: type=docker
          tags: |
            my_image:latest
      - name: Test
        run: |
          docker run --rm my_image:latest ls -la exclude_me/do_not_want.txt